### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by FenixGit** [eigenein/joypad-android#1]
Hello, I am not able to use the plugin in android studio 3.1.2, the message appears: Failed to resolve: com.github.eigenein:joypad-android:5

**Comment by eigenein** [comment]
Hello, works for me in a clean project. Make sure you follow the steps to include JitPack repo: https://jitpack.io/#eigenein/joypad-android/5

**Comment by FenixGit** [comment]
Hello @eigenein 
It's working now, thank you.
The only difference was to switch from dependencies to allprojects

best regards
